name: 'Delete old artifacts'
on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
jobs:
  delete-artifacts:
    uses: syedsalman3753/kattu/.github/workflows/clear-artifacts.yml@master
    #secrets: inherit
